# Form implementation generated from reading ui file 'C:\Users\fritt\OneDrive\Документы\Py\conv\game.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(871, 819)
        MainWindow2.setStyleSheet("background-color: #000000")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(200, 0, 471, 271))
        self.frame.setStyleSheet("background-color: #ffff00;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: black")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(110, 30, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.itog = QtWidgets.QLineEdit(parent=self.frame)
        self.itog.setGeometry(QtCore.QRect(40, 140, 391, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        self.itog.setFont(font)
        self.itog.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.itog.setObjectName("itog")
        self.odin = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.odin.setGeometry(QtCore.QRect(240, 310, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.odin.setFont(font)
        self.odin.setStyleSheet("color: black;\n"
"background-color: #ffff00;")
        self.odin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.odin.setObjectName("odin")
        self.dva = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.dva.setGeometry(QtCore.QRect(240, 410, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dva.setFont(font)
        self.dva.setStyleSheet("color: black;\n"
"background-color: #ffff00;")
        self.dva.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dva.setObjectName("dva")
        self.tri = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tri.setGeometry(QtCore.QRect(240, 510, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tri.setFont(font)
        self.tri.setStyleSheet("color: black;\n"
"background-color: #ffff00;")
        self.tri.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tri.setObjectName("tri")
        self.btnItog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnItog.setGeometry(QtCore.QRect(240, 600, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnItog.setFont(font)
        self.btnItog.setStyleSheet("border: 2px solid #f66867;\n"
"border-radius: 30;")
        self.btnItog.setObjectName("btnItog")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 25))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "MainWindow"))
        self.label.setText(_translate("MainWindow2", "Результат"))
        self.btnItog.setText(_translate("MainWindow2", "Тык-Тык"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec())
