# Form implementation generated from reading ui file 'C:\Users\fritt\OneDrive\Документы\Py\conv\converter.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 845)
        MainWindow.setStyleSheet("background-color: #22222e")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: #22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 881, 270))
        self.frame.setStyleSheet("background-color: #fb5b5d ")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(300, 0, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 751, 371))
        self.label_2.setStyleSheet("backround-color: #22222e")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\fritt\\OneDrive\\Документы\\Py\\conv\\../../../../Downloads/tiMtjoTp2BIhVXHXyg24yqgF0vLQABkwhKkthPFVBmU85Cl63iIthIDsB4VKiV6KnrZBA-O1CfM7wHRSgIgeU1r6.jpg"))
        self.label_2.setObjectName("label_2")
        self.imput_cur = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.imput_cur.setGeometry(QtCore.QRect(250, 310, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setItalic(False)
        self.imput_cur.setFont(font)
        self.imput_cur.setStyleSheet("backround-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white; backround-color: #22222e")
        self.imput_cur.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imput_cur.setObjectName("imput_cur")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 710, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: #fb5b5d;\n"
"border-radius: 30px;\n"
"color: white;\n"
"}\n"
"QPushButton: pressed {\n"
"background-color: #fa4244;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.imput_sum = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.imput_sum.setGeometry(QtCore.QRect(250, 400, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setItalic(False)
        self.imput_sum.setFont(font)
        self.imput_sum.setStyleSheet("backround-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white; backround-color: #22222e")
        self.imput_sum.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imput_sum.setObjectName("imput_sum")
        self.output_sum = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.output_sum.setGeometry(QtCore.QRect(250, 500, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setItalic(False)
        self.output_sum.setFont(font)
        self.output_sum.setStyleSheet("backround-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white; backround-color: #22222e")
        self.output_sum.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_sum.setObjectName("output_sum")
        self.output_cur = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.output_cur.setGeometry(QtCore.QRect(250, 600, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setItalic(False)
        self.output_cur.setFont(font)
        self.output_cur.setStyleSheet("backround-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white; backround-color: #22222e")
        self.output_cur.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_cur.setObjectName("output_cur")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Конверт валют"))
        self.pushButton.setText(_translate("MainWindow", "Конвертация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
